proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /usr/local/vecta-website/default_proxy_configuration.conf:/etc/nginx/conf.d/default_proxy_configuration.conf:ro
web:
  image: wordpress
  links:
    - mysql
  environment:
    VIRTUAL_HOST: "vecta.tv,www.vecta.tv"
    WORDPRESS_DB_PASSWORD: "vecta-wordpress-db-pw"
mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: "vecta-wordpress-db-pw"
    MYSQL_DATABASE: "wordpress"
  volumes:
    - /usr/local/vecta/mysql:/var/lib/mysql